version: "2"
services:

  sui:
    container_name: sui
    restart: always
    build:
      context: ./
    environment:
      - VIRTUAL_HOST=test.laserr.net
    networks:
      - bridge
    ports:
      - 4000:80
    volumes:
      - ./:/usr/share/nginx/html

